name: power_extensions
description: Extensions for the core dart language classes.
version: 0.2.4
homepage: https://github.com/giorgiofran/power_extensions.git

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
